[package]
name = "pixelbin-shared"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = "2.1.0"
diesel-async = { version = "0.4.1", features = ["deadpool"] }
diesel_migrations = "2.1.0"
handlebars = "4.3.7"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
thiserror = "1.0.40"
chrono = { version = "0.4.31", features = ["serde"] }
tracing = { version = "0.1.37", features = ["attributes"] }
