[package]
name = "pixelbin-shared"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = "2.0.4"
diesel-async = { version = "0.2.2", features = ["deadpool"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
thiserror = "1.0.40"
tracing = { version = "0.1.37", features = ["attributes"] }
