version: "3.7"

services:

  redis:
    image: redis

  celery:
    build:
      context: .
      dockerfile: docker/celery/Dockerfile
    volumes:
      - "$PWD/api:/usr/src/pixelbin/api:ro"
      - "$PWD/app:/usr/src/pixelbin/app:ro"
      - "$PWD/base:/usr/src/pixelbin/base:ro"
      - "$PWD/config:/usr/src/pixelbin/config:ro"
      - "$PWD/public/static:/usr/src/pixelbin/public/static:ro"
      - "$PWD/config.ini:/usr/src/pixelbin/config.ini:ro"
      - "$PWD/data:/usr/src/pixelbin/data:rw"
      - "$PWD/public/media:/usr/src/pixelbin/public/media:rw"

  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    ports:
      - "8000:8000/tcp"
    volumes:
      - "$PWD/api:/usr/src/pixelbin/api:ro"
      - "$PWD/app:/usr/src/pixelbin/app:ro"
      - "$PWD/base:/usr/src/pixelbin/base:ro"
      - "$PWD/config:/usr/src/pixelbin/config:ro"
      - "$PWD/public/static:/usr/src/pixelbin/public/static:ro"
      - "$PWD/config.ini:/usr/src/pixelbin/config.ini:ro"
      - "$PWD/data:/usr/src/pixelbin/data:rw"
      - "$PWD/public/media:/usr/src/pixelbin/public/media:rw"
