version: "3.7"

services:

  redis:
    image: redis

  celery:
    build:
      context: .
      dockerfile: docker/celery/Dockerfile
    volumes:
      - "$PWD/api:/usr/src/pixelbin/api:ro"
      - "$PWD/app:/usr/src/pixelbin/app:ro"
      - "$PWD/base:/usr/src/pixelbin/base:ro"
      - "$PWD/config:/usr/src/pixelbin/config:ro"
      - "$PWD/public:/usr/src/pixelbin/public:ro"
      - "$PWD/config.ini:/usr/src/pixelbin/config.ini:ro"
      - "$PWD/pixelbin.sqlite:/usr/src/pixelbin/pixelbin.sqlite"

  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    ports:
      - "8000:8000/tcp"
    volumes:
    volumes:
      - "$PWD/api:/usr/src/pixelbin/api:ro"
      - "$PWD/app:/usr/src/pixelbin/app:ro"
      - "$PWD/base:/usr/src/pixelbin/base:ro"
      - "$PWD/config:/usr/src/pixelbin/config:ro"
      - "$PWD/public:/usr/src/pixelbin/public:ro"
      - "$PWD/config.ini:/usr/src/pixelbin/config.ini:ro"
      - "$PWD/pixelbin.sqlite:/usr/src/pixelbin/pixelbin.sqlite"
