version: "3.7"

services:

  redis:
    image: redis

  celery:
    build: ./docker/celery
    volumes:
      - "$PWD:/usr/src/pixelbin"

  server:
    build: ./docker/testserver
    ports:
      - "8000:8000/tcp"
    volumes:
      - "$PWD:/usr/src/pixelbin"
