[tools]
node = "22"
watchexec = "latest"

[env]
DATABASE_URL = "postgres://pixelbin:pixelbin@localhost/pixelbin"

[tasks.syncdata]
description = "Sync local and temp storage"
run = "./sync"
dir = "testing"

[tasks.apiserver]
description = "Run the API server"
run = "cargo run -p pixelbin_cli -- serve"
sources = [
  "packages/shared/Cargo.toml",
  "packages/shared/src/**/*.rs",
  "packages/migrations/Cargo.toml",
  "packages/migrations/src/**/*.rs",
  "packages/service/Cargo.toml",
  "packages/service/src/**/*.rs",
  "packages/cli/Cargo.toml",
  "packages/cli/src/**/*.rs",
]

[tasks.apiserver.env]
PIXELBIN_DATABASE_URL = "postgres://pixelbin:pixelbin@localhost/pixelbin"
PIXELBIN_MAIL_SERVER = "postfix.clantownsend.com:25"
PIXELBIN_STORAGE = "testing/data/pixelbin"
PIXELBIN_TELEMETRY_HOST = "http://localhost:4318/v1/traces"
PIXELBIN_TESTING = true
PIXELBIN_MAIL_ADDRESS = "Pixelbin <noreply@pixelbin.org>"

[tasks.webserver]
description = "Run the web server"
run = "npm run dev"
dir = "packages/webapp"
sources = [
  "packages/webapp/package.json",
  "packages/webapp/instrumentation.mjs",
  "packages/webapp/**/*.ts",
]

[tasks.webserver.env]
PIXELBIN_TELEMETRY_HOST = "http://localhost:4318/v1/traces"
PIXELBIN_API_URL = "http://localhost:8283"

[tasks.lint]
description = "Lint the webapp"
run = "npm run lint"
sources = [
  "packages/webapp/**/*.json",
  "packages/webapp/**/*.ts",
  "packages/webapp/**/*.tsx",
  "packages/webapp/**/*.js",
  "packages/webapp/**/*.jsx",
  "packages/webapp/**/*.cjs",
  "packages/webapp/**/*.mjs",
]

[tasks.typecheck]
description = "Typecheck the webapp"
run = "npm run typecheck"
sources = [
  "packages/webapp/**/*.json",
  "packages/webapp/**/*.ts",
  "packages/webapp/**/*.tsx",
  "packages/webapp/**/*.js",
  "packages/webapp/**/*.jsx",
  "packages/webapp/**/*.cjs",
  "packages/webapp/**/*.mjs",
]
