version: '3'

services:
  postgres:
    image: postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: pixelbin
      POSTGRES_PASSWORD: pixelbin

    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5

    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pixelbin.org
      PGADMIN_DEFAULT_PASSWORD: pixelbin
      PGADMIN_LISTEN_PORT: 7000

    ports:
      - 7000:7000

    volumes:
      - ../testrun/pgadmin.json:/pgadmin4/servers.json

  redis:
    image: redis
    restart: unless-stopped

    ports:
      - 6379:6379

    command: redis-server --appendonly yes

  minio:
    image: minio/minio
    restart: unless-stopped

    # Not really, but it makes docker-compose wait for postgres to become available before quitting.
    depends_on:
      postgres:
        condition: service_healthy

    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      MINIO_REGION_NAME: us-west-001

    ports:
      - 9000:9000

    command: server /data
