[package]
name = "pixelbin"
version = "0.1.0"
edition = "2021"

[features]
default = ["webserver"]
webserver = [
  "dep:actix-web",
  "dep:actix-multipart",
  "dep:mime_guess",
  "dep:nano-id",
  "dep:serde_with",
  "dep:mime",
  "dep:tokio-util",
  "dep:file-format",
]

[dependencies]
clap = { version = "4.4.10", features = ["derive", "env"] }
tokio = { version = "1.28.1", features = ["full"] }
tracing = { version = "0.1.40", features = ["attributes"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
async-trait = "0.1.68"
thiserror = "1.0.40"
enum_dispatch = "0.3.11"
opentelemetry = "0.23.0"
opentelemetry_sdk = { version = "0.23.0", features = ["rt-tokio"] }
tracing-opentelemetry = "0.24.0"
opentelemetry-otlp = { version = "0.16.0", features = ["http-proto", "reqwest-client"] }
scoped-futures = "0.1.3"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
diesel = { version = "2.1.0", features = [
  "64-column-tables",
  "chrono",
  "serde_json",
  "postgres",
] }
diesel-async = { version = "0.4.1", features = ["postgres", "deadpool"] }
diesel-derive-enum = "2.0.1"
aws-sdk-s3 = "1.4.0"
aws-config = "1.0.1"
futures = "0.3.28"
chrono = { version = "0.4.31", features = ["clock", "serde", "clock"] }
bcrypt = "0.15.0"
monostate = "0.1.6"
serde_repr = "0.1.12"
serde_plain = "1.0.1"
typeshare = "1.0.1"
diesel_migrations = { version = "2.1.0", features = ["postgres"] }
tzf-rs = { version = "0.4.4", default-features = false }
lazy_static = "1.4.0"
lexical-parse-float = "0.8.5"
chrono-tz = "0.8.4"
tempfile = "^3.4"
image = { version = "0.24.8", features = ["avif"] }
async-channel = "2.1.1"
figment = { version = "0.10.15", features = ["json", "env"] }
dotenvy = "0.15.7"
strum_macros = "0.26.2"

actix-web = { version = "4.3.1", optional = true }
actix-multipart = { version = "0.6.1", optional = true }
mime_guess = { version = "2.0.4", optional = true }
nano-id = { version = "0.3.1", features = ["base62"], optional = true }
serde_with = { version = "3.0.0", optional = true }
mime = { version = "0.3.17", optional = true }
tokio-util = { version = "0.7.8", features = ["io"], optional = true }
file-format = { version = "0.23.0", features = ["reader-mp4"], optional = true }
webp = "0.2.7"
