#! /bin/sh

EXEC="sudo --user=pixelbin"

set -e
echo "Installing python dependencies..."
pip install -q -r requirements.txt
echo "Installing npm dependencies..."
${EXEC} npm install

${EXEC} ./manage.py collectstatic --no-input
${EXEC} node_modules/.bin/webpack --config app/webpack.config.js
${EXEC} ./manage.py makemigrations
${EXEC} ./manage.py migrate

echo "Starting test server..."
trap 'trap - TERM; kill -1' TERM
${EXEC} ./manage.py runserver --nostatic 0.0.0.0:8000 &
wait
exit 0
