#! /bin/sh

EXEC="sudo --user=pixelbin"

set -e
echo "Installing python dependencies..."
pip install -q -r requirements.txt

echo "Starting celery..."
trap 'trap - TERM; kill -1' TERM
${EXEC} celery -A api worker -l info &
wait
exit 0
