[package]
name = "pixelbin-store"
version = "0.1.0"
edition = "2021"

[dependencies]
pixelbin-shared = { path = "../shared" }
diesel = { version = "2.0.4", features = ["64-column-tables", "time", "serde_json"] }
diesel-async = { version = "0.2.2", features = ["postgres", "deadpool"] }
thiserror = "1.0.40"
tracing = { version = "0.1.37", features = ["attributes"] }
diesel-derive-enum = "2.0.1"
aws-sdk-s3 = "0.27.0"
aws-config = "0.55.3"
futures = "0.3.28"
time = "0.3.21"
tokio = { version = "1.28.1", features = ["fs"] }
bcrypt = "0.14.0"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
async-trait = "0.1.68"
