[package]
name = "pixelbin-store"
version = "0.1.0"
edition = "2021"

[dependencies]
pixelbin-shared = { path = "../shared" }
diesel = { version = "2.0.4", features = ["64-column-tables"] }
diesel-async = { version = "0.2.2", features = ["postgres", "deadpool"] }
thiserror = "1.0.40"
tracing = { version = "0.1.37", features = ["attributes"] }
