[package]
name = "pixelbin-store"
version = "0.1.0"
edition = "2021"

[dependencies]
pixelbin-shared = { path = "../shared" }
diesel = { version = "2.1.0", features = ["64-column-tables", "chrono", "serde_json", "postgres"] }
diesel-async = { version = "0.4.1", features = ["postgres", "deadpool"] }
thiserror = "1.0.40"
tracing = { version = "0.1.37", features = ["attributes"] }
diesel-derive-enum = "2.0.1"
aws-sdk-s3 = "0.27.0"
aws-config = "0.55.3"
futures = "0.3.28"
chrono = { version = "0.4.31", features = ["clock", "serde"] }
tokio = { version = "1.28.1", features = ["fs"] }
bcrypt = "0.14.0"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
async-trait = "0.1.68"
monostate = "0.1.6"
serde_repr = "0.1.12"
serde_plain = "1.0.1"
typeshare = "1.0.1"
diesel_migrations = { version = "2.1.0", features = ["postgres"] }
tzf-rs = { version = "0.4.4", default-features = false }
lazy_static = "1.4.0"
lexical-parse-float = "0.8.5"
chrono-tz = "0.8.4"
