[package]
name = "pixelbin-tasks"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = { version = "0.1.37", features = ["attributes"] }
pixelbin-store = { path = "../store" }
pixelbin-shared = { path = "../shared" }
tokio = { version = "1.28.1", features = ["fs"] }
scoped-futures = "0.1.3"
serde = { version = "1.0.163", features = ["derive"] }
