[package]
name = "pixelbin-tasks"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = { version = "0.1.37", features = ["attributes"] }
pixelbin-store = { path = "../store" }
pixelbin-shared = { path = "../shared" }
tokio = { version = "1.28.1", features = ["fs"] }
scoped-futures = "0.1.3"
time = { version = "0.3.30", features = ["serde"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
serde-aux = "4.2.0"
tzf-rs = { version = "0.4.4", default-features = false }
lazy_static = "1.4.0"
lexical-parse-float = "0.8.5"
