[package]
name = "pixelbin-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = { version = "0.1.37", features = ["attributes"] }
pixelbin-store = { path = "../store" }
pixelbin-shared = { path = "../shared" }
actix-web = "4.3.1"
