[package]
name = "pixelbin-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = { version = "0.1.37", features = ["attributes"] }
pixelbin-store = { path = "../store" }
pixelbin-shared = { path = "../shared" }
actix-web = "4.3.1"
handlebars = "4.3.7"
rust-embed = "6.6.1"
mime_guess = "2.0.4"
serde = "1.0.163"
futures = "0.3.28"
actix-session = { version = "0.7.2", features = ["cookie-session"] }
