[package]
name = "pixelbin-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = { version = "0.1.37", features = ["attributes"] }
pixelbin-store = { path = "../store" }
pixelbin-shared = { path = "../shared" }
actix-web = "4.3.1"
handlebars = "4.3.7"
rust-embed = "6.6.1"
mime_guess = "2.0.4"
serde = "1.0.163"
futures = "0.3.28"
actix-session = { version = "0.7.2", features = ["cookie-session"] }
tokio = { version = "1.28.2", features = ["sync", "fs"] }
nano-id = { version = "0.3.1", features = ["base62"] }
serde_json = "1.0.96"
serde_with = "3.0.0"
scoped-futures = "0.1.3"
mime = "0.3.17"
time = { version = "0.3.22", features = ["formatting", "parsing"] }
tokio-util = { version = "0.7.8", features = ["io"] }
askama = "0.12.0"
