[package]
name = "pixelbin-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
pixelbin-store = { path = "../store" }
clap = { version = "4.3.0", features = ["derive", "env"] }
tokio = { version = "1.28.1", features = ["full"] }
tracing = { version = "0.1.37", features = ["attributes"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
