[package]
name = "pixelbin-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
pixelbin-shared = { path = "../shared" }
pixelbin-tasks = { path = "../tasks" }
pixelbin-store = { path = "../store" }
pixelbin-server = { path = "../server" }
clap = { version = "4.3.0", features = ["derive", "env"] }
tokio = { version = "1.28.1", features = ["full"] }
tracing = { version = "0.1.37", features = ["attributes"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
async-trait = "0.1.68"
thiserror = "1.0.40"
enum_dispatch = "0.3.11"
opentelemetry = { version = "0.19.0", features = ["rt-tokio"] }
tracing-opentelemetry = "0.19.0"
opentelemetry-otlp = "0.12.0"
scoped-futures = "0.1.3"
