[package]
name = "pixelbin_cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pixelbin"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.16", features = ["derive", "env"] }
tokio = { version = "1.39.3", features = ["full"] }
tracing-subscriber = { version = "0.3.18" }
pixelbin = { path = "../service", features = ["webserver"] }
dotenvy = "0.15.7"
enum_dispatch = "0.3.13"
opentelemetry = "0.27.1"
tracing-opentelemetry = "0.28.0"
opentelemetry-otlp = { version = "0.27.0", features = [
  "http-proto",
  "reqwest-client",
] }
tracing = { version = "0.1.40", features = ["attributes"] }
opentelemetry_sdk = { version = "0.27.1", features = ["rt-tokio"] }
