name: Commit checks

on: [push, pull_request]

env:
  NODE_VERSION: '14'

jobs:
  jest-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: pixelbin
          POSTGRES_PASSWORD: pixelbin
          POSTGRES_DB: pixelbin_test
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      minio:
        image: mossop/minio-server
        env:
          MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
          MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
          MINIO_REGION_NAME: us-west-001
        ports:
          - 9000:9000

    steps:
    - name: Setup data directory
      run: |
        docker container ls
        container=$(docker container ls -q --filter "publish=9000")
        docker exec ${container} mkdir /data/pixelbin

    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: |
          ~/.npm
          node_modules
        key: ${{ runner.os }}-${{ env.NODE_VERSION }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.NODE_VERSION }}-${{ env.cache-name }}-

    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install ffmpeg

    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Show versions
      run: |
        node --version
        npm --version

    - name: Install node packages
      run: |
        npm install -g gulp
        npm install

    - name: Run tests
      run: |
        gulp testClientJest
        gulp testServer

    - name: Upload code coverage
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        bash <(curl -s https://codecov.io/bash) -f coverage/coverage-final.json -F jest

    - name: Run lint checks
      run: |
        gulp lint

  karma-tests:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: |
          ~/.npm
          node_modules
        key: ${{ runner.os }}-${{ env.NODE_VERSION }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.NODE_VERSION }}-${{ env.cache-name }}-

    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Show versions
      run: |
        node --version
        npm --version

    - name: Install node packages
      run: |
        npm install -g gulp
        npm install

    - name: Run tests
      run: |
        gulp testClientKarma

    - name: Upload code coverage
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        bash <(curl -s https://codecov.io/bash) -f coverage/coverage-final.json -F karma
