name: Commit checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Node.js 12
      uses: actions/setup-node@v1.4.1
      with:
        node-version: 12.x

    - name: Setup Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Show versions
      run: |
        node --version
        python --version

    - name: Install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_dev.txt

    - name: Install node packages
      run: npm install

    - name: Run lint checks
      run: gulp lint

  server-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Show versions
      run: |
        node --version
        python --version

    - name: Install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
        pip install -r requirements_postgres.txt

    - name: Run tests
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost/pixelbin
      run: |
        ./manage.py test
