name: Commit checks

on: [push, pull_request]

env:
  NODE_VERSION: '14'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Show versions
      run: |
        echo "Node $(node --version)"
        echo "NPM $(npm --version)"

    - name: Install node packages
      run: |
        npm install

    - name: Run lint checks
      run: |
        ./node_modules/.bin/eslint --ext .ts,.tsx,.js,.jsx .

  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Show versions
      run: |
        node --version
        npm --version

    - name: Install node packages
      run: |
        npm install -g gulp
        npm install

    - name: Run tests
      run: |
        gulp test

    - name: Upload code coverage
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        bash <(curl -s https://codecov.io/bash) -f coverage/coverage-final.json
