name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.1
      with:
        node-version: 10.x

    - name: Install python packages
      run: pip3 install -r requirements.txt

    - name: Install node packages
      run: npm install

    - name: Run lint checks
      run: gulp lint
