name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Pull submodules
      run: |
        git submodule init
        git submodule update

    - name: Setup Node.js 12
      uses: actions/setup-node@v1.4.1
      with:
        node-version: 12.x

    - name: Setup Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Show versions
      run: |
        node --version
        python --version
        python3 --version
        pip3 --version

    - name: Install python packages
      run: |
        pip3 install -r requirements.txt
        pip3 install -r requirements_dev.txt

    - name: Show python info
      run: |
        pip3 --version
        pip3 show pylint
        echo $PATH

    - name: Install node packages
      run: npm install

    - name: Run lint checks
      run: gulp lint
