name: Build plugin

on:
  workflow_dispatch: {}
  push:
    tags:
      - 'v*'

jobs:
  build-plugin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          node build_plugin.mjs ${{ github.ref_name }}

      - name: Push artifact
        uses: actions/upload-artifact@v4
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        with:
          name: LrPixelbin
          compression-level: 9
          path: |
            build/

      - name: Package
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd build && zip -r9 ../LrPixelbin-${{ github.ref_name }}.zip *

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            LrPixelbin-${{ github.ref_name }}.zip
