name: Build server

on:
  workflow_dispatch: {}
  push:
    tags:
      - 'v*'

jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/mossop/pixelbin-server
          tags: |
            type=semver,pattern=v{{major}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}.{{minor}}.{{patch}}
            type=ref,event=branch
          labels: |
            org.opencontainers.image.title=Pixelbin Server
            org.opencontainers.image.description=The Pixelbin API server

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGE_TOKEN }}

      - name: Cache mounts
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            cache-registry
            cache-target
          key: cache-${{ hashFiles('packages/service/Dockerfile') }}

      - name: Inject cache mounts into docker
        uses: reproducible-containers/buildkit-cache-dance@v3.1.0
        with:
          cache-map: |
            {
              "cache-registry": "/usr/local/cargo/registry",
              "cache-target": "/build/target"
            }
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: packages/service/Dockerfile
          platforms: linux/amd64
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
            SOURCE_CHANGESET=${{ github.sha }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
