name: Build webapp

on:
  workflow_dispatch: {}
  push:
    tags:
      - 'v*'

jobs:
  build-webapp:
    runs-on: ubuntu-latest

    steps:
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/mossop/pixelbin-webapp
          tags: |
            type=semver,pattern=v{{major}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}.{{minor}}.{{patch}}
            type=ref,event=branch
          labels: |
            org.opencontainers.image.title=Pixelbin Webapp
            org.opencontainers.image.description=A Remix webapp to access Pixelbin

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGE_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: packages/webapp/Dockerfile
          platforms: linux/amd64
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
            SOURCE_CHANGESET=${{ github.sha }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
